./install/desktop.sh
./install/yay.sh
./install/theme.sh
./install/terminal.sh
./install/config.sh
./install/asdf.sh
./install/gsettings.sh
./install/gnome_extensions.sh
./install/packages.sh
./install/east_asian_fonts.sh